### ISSUE TITLE
US4 As a user, I want to fill in my contacts MUST

### ISSUE THREAD

**Issue by Frodan** [screemix/map_book_friending_app#17]
- [x] Agree on databases fields #12 
- [x] Launch databases #3 
- [x] Write frontend for filling in contact information #20
- [x] Write backend for filling in contact information #22
