### ISSUE TITLE
US5 As a user I want to my contact information be displayed for other users MUST

### ISSUE THREAD

**Issue by Frodan** [screemix/map_book_friending_app#21]
- [x] Agree on databases fields #12 
- [x] Launch databases #3 
- [x] Write frontend for user profile #18
- [x] Write backend for user profile #19
