### ISSUE TITLE
US6  As a user I want to search for users with similar book tastes MUST

### ISSUE THREAD

**Issue by Frodan** [screemix/map_book_friending_app#23]
- [x] Write script with ML model for ranking users #26 
- [x] Write frontend for search #29
- [x] Write backend for search #31
- [x] #61
- [x] #62
- [x] #63
- [x] #64
- [x] #65
